#!/bin/bash

# @License EPL-1.0 <http://spdx.org/licenses/EPL-1.0>
##############################################################################
# Copyright (c) 2016 Company and Others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
##############################################################################

##############################################################################
# Define Defaults
##############################################################################

##############################################################################
# Define Variables
##############################################################################
BUILD_PHASE=${1-package}

##############################################################################
# Show Usage
##############################################################################
usage () {
  echo "AsciiDocs to ReStructuredText Converter Application"
  echo "usage: adoc2rst [<phase>]"
  echo "Phases:"
  echo "    help    Display command line usage information."
  echo "    clean   Clean project binaries."
  echo "    package Build project binaries."
}

##############################################################################
# Clean Adoc2Rst
##############################################################################
clean () {
  rm -rf bin
  rm -rf sample
  mvn clean
}

##############################################################################
# Package Adoc2Rst
##############################################################################
package () {
  mkdir -p bin
  if [ ! -d "$DIRECTORY" ]; then
    git clone https://git.opendaylight.org/gerrit/docs.git sample
  fi
  mvn package
  java -jar ./target/adoc2rst.jar
}

if [ "${BUILD_PHASE}" = "help" ]; then
  usage
elif [ "${BUILD_PHASE}" = "clean" ]; then
  clean
elif [ "${BUILD_PHASE}" = "package" ]; then
  package
else
  usage
fi

